<a href="https://colab.research.google.com/github/nazgul19/big_data/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
"""question 1"""
import numpy as np
arr = np.array([1,2,4,5])
brr = arr[::-1]
print(brr)

[5 4 2 1]


In [52]:
brr = arr[::-1]
print(brr)

[5 4 2 1]


In [54]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [55]:
check = np.greater_equal(arr1,arr2)
print(check.all())

True


In [56]:
x = np.array([1,2,3,4,5,1,2,2,2,2])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [57]:
print(np.bincount(x).argmax())

2


In [58]:
print(np.bincount(y).argmax())

1


In [59]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1;4, 5, 6]')
print(gfg.sum())

45


In [60]:
print(gfg.sum(axis=0))

[[20  9 16]]


In [61]:
print(gfg.sum(axis = 1))

[[14]
 [16]
 [15]]
