<a href="https://colab.research.google.com/github/nazgul19/big_data/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("helloo")

helloo


In [ ]:
print("hello")

hello


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,4,5])
print(arr[::-1])

[5 4 2 1]


In [ ]:
print(arr[-1::-1])

[5 4 2 1]


In [13]:
print("hello")

hello


In [14]:
arr = np.array([1,2,4,5])

In [15]:
brr = arr[::-1]
print(brr)

[5 4 2 1]


In [16]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [18]:
cmp = arr1==arr2
print(cmp.all())

True


In [20]:
check = np.greater_equal(arr1,arr2)
print(check.all())

True


In [28]:
x = np.array([1,2,3,4,5,1,2,2,2,2])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [29]:
print(np.bincount(x).argmax())

2


In [27]:
print(np.bincount(x).argmax())

1


In [37]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1;4, 5, 6]')
print(gfg.sum())

45


In [47]:
print(gfg.sum(axis=0))

[[20  9 16]]


In [42]:
print(gfg.sum(axis = 1))

[[14]
 [16]
 [15]]


In [44]:
print(gfg)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
